---
- name: Install helm chart argocd
  helm:
    name: argocd
    chart_ref: argo/argo-cd
    chart_version: 2.9.3
    release_namespace: "{{ argocd_namespace }}"
    values: "{{ lookup('template', 'argocd/argocd-values.yaml') | from_yaml }}"

- name: Ensure argocd crds exist
  command: "kubectl get crd"
  register: argocd_crds
  until: "argocd_crds.stdout | regex_findall('.*argoproj.io') | length == 2"
  retries: 10
  delay: 10
  changed_when: false
  become: true
