---
- name: Install helm chart kube-prometheus-stack
  helm:
    name: kube-prometheus-stack
    chart_ref: prometheus-community/kube-prometheus-stack
    chart_version: 9.4.1
    release_namespace: "{{ kube_prometheus_stack_namespace }}"
    values: "{{ lookup('template', 'kube-prometheus-stack/kube-prometheus-stack-values.yaml') | from_yaml }}"

- name: Ensure kube-prometheus-stack crds exist
  command: "kubectl get crd"
  register: kube_prometheus_stack_crds
  until: "kube_prometheus_stack_crds.stdout | regex_findall('.*monitoring.coreos.com') | length == 6"
  retries: 10
  delay: 10
  changed_when: false
  become: true

- name: Create kube-prometheus-stack ingressroutes
  k8s:
    state: present
    definition: "{{ lookup('template', 'traefik/traefik-ingressroute.yaml') }}"
  with_items:
    - name: alertmanager
      namespace: "{{ kube_prometheus_stack_namespace }}"
      routes:
        - rule: Host(`{{ alertmanager_hostname }}`)
          middlewares:
            - name: forward-auth
              namespace: "{{ traefik_namespace }}"
            - name: allow-lan-only@file
          services:
            - name: kube-prometheus-stack-alertmanager
              port: 9093
    - name: prometheus
      namespace: "{{ kube_prometheus_stack_namespace }}"
      routes:
        - rule: Host(`{{ prometheus_hostname }}`)
          middlewares:
            - name: forward-auth
              namespace: "{{ traefik_namespace }}"
            - name: allow-lan-only@file
          services:
            - name: kube-prometheus-stack-prometheus
              port: 9090
