---
- name: Ensure local-path-provisioner directories exist
  file:
    path: "{{ item.path }}"
    owner: root
    group: root
    state: directory
  become: true
  with_items: "{{ local_path_provisioner_data_paths }}"

- name: Install helm charts local-path-provisioner
  helm:
    name: "{{ item.name }}"
    chart_ref: containeroo/local-path-provisioner
    chart_version: 0.0.17
    release_namespace: "{{ local_path_provisioner_namespace }}"
    values: "{{ lookup('template', 'local-path-provisioner/local-path-provisioner-values.yaml') | from_yaml }}"
  with_items: "{{ local_path_provisioner_data_paths }}"
