---
- name: Create minio credentials secret
  k8s:
    state: present
    definition: "{{ lookup('template', 'minio/minio-credentials-secret.yaml') }}"

- name: Install helm chart minio
  helm:
    name: minio
    chart_ref: minio/minio
    chart_version: 7.2.1
    release_namespace: "{{ minio_namespace }}"
    values: "{{ lookup('template', 'minio/minio-values.yaml') | from_yaml }}"
