---
- name: Install helm chart backup nfs-client-provisioner
  helm:
    name: backup
    chart_ref: stable/nfs-client-provisioner
    chart_version: 1.2.8
    release_namespace: "{{ nfs_client_provisioner_namespace }}"
    values: "{{ lookup('template', 'nfs-client-provisioner/nfs-client-provisioner-values.yaml') | from_yaml }}"
