---
- name: Install helm chart prometheus-pushgateway
  helm:
    name: prometheus-pushgateway
    chart_ref: prometheus-community/prometheus-pushgateway
    chart_version: 1.4.2
    release_namespace: "{{ prometheus_pushgateway_namespace }}"
    values: "{{ lookup('template', 'prometheus-pushgateway/prometheus-pushgateway-values.yaml') | from_yaml }}"
