serviceMonitor:
  enabled: true
  namespace: {{ prometheus_operator_namespace }}
  additionalLabels:
    prometheus: default
persistentVolume:
  enabled: true
  storageClass: {{ prometheus_pushgateway_storageclass }}
