apiVersion: v1
stringData:
  accesskey: {{ backup_minio_accesskey }}
  secretkey: {{ backup_minio_secretkey }}
kind: Secret
metadata:
  name: backup-minio-credentials
  namespace: {{ backup_minio_namespace }}
type: Opaque
