apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ item.name }}
  namespace: {{ item.namespace }}
spec:
  entryPoints:
    - websecure
  routes:
{% for route in item.routes %}
    - kind: Rule
      match: {{ route.rule }}
{% if route.middlewares is defined %}
      middlewares:
{% for middleware in route.middlewares %}
        - name: {{ middleware.name }}
          namespace: {{ middleware.namespace | default(omit) }}
{% endfor %}
{% endif %}
      services:
{% for service in route.services %}
        - name: {{ service.name }}
          port: {{ service.port }}
{% endfor %}
{% endfor %}
