existingSecret: minio-credentials
persistence:
  storageClass: backup
{% if minio_buckets is not none %}
buckets:
{% for bucket in minio_buckets %}
  - name: {{ bucket }}
    policy: none
    purge: false
{% endfor %}
{% endif %}
environment:
  TZ: {{ timezone }}
