nodePathMap:
  - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
    paths:
      - {{ item.path }}
storageClass:
  defaultClass: {{ item.defaultClass }}
  name: {{ item.name }}
configmap:
  name: {{ item.name }}-local-path-provisioner
  teardown: |-
    #!/bin/sh
    while getopts "m:s:p:" opt
    do
      case $opt in
        p)
        absolutePath=$OPTARG
        ;;
        s)
        sizeInBytes=$OPTARG
        ;;
        m)
        volMode=$OPTARG
        ;;
        esac
    done

    archived_path="$(dirname ${absolutePath})/archived-$(basename ${absolutePath})"
    mv ${absolutePath} ${archived_path}
