apiVersion: backup.appuio.ch/v1alpha1
kind: Schedule
metadata:
  name: cluster-resources-backup
  namespace: {{ k8up_namespace }}
spec:
  backend:
    s3:
      bucket: cluster-resources
  backup:
    schedule: "{{ cluster_resources_backup_schedule }}"
  check:
    schedule: "{{ cluster_resources_backup_check_schedule }}"
  prune:
    retention:
      keepDaily: {{ cluster_resources_backup_keep_daily }}
      keepLast: {{ cluster_resources_backup_keep_last }}
    schedule: "{{ cluster_resources_backup_prune_schedule }}"
