k8up:
  timezone: {{ timezone }}
  envVars:
    - name: BACKUP_GLOBALREPOPASSWORD
      value: {{ k8up_restic_password }}
    - name: BACKUP_GLOBALACCESSKEYID
      value: {{ minio_accesskey }}
    - name: BACKUP_GLOBALSECRETACCESSKEY
      value: {{ minio_secretkey }}
    - name: BACKUP_GLOBALS3ENDPOINT
      value: http://minio.{{ minio_namespace }}.svc.cluster.local:9000
    - name: BACKUP_GLOBALKEEPJOBS
      value: "{{ k8up_keep_jobs }}"
    - name: BACKUP_PROMURL
      value: http://prometheus-pushgateway.{{ prometheus_pushgateway_namespace }}.svc.cluster.local:9091
metrics:
  serviceMonitor:
    enabled: true
    namespace: {{ kube_prometheus_stack_namespace }}
    additionalLabels:
      prometheus: default
  prometheusRule:
    enabled: true
    namespace: {{ kube_prometheus_stack_namespace }}
    additionalLabels:
      prometheus: default
