k8up:
  backupImage:
    tag: v0.1.9
  envVars:
    - name: BACKUP_GLOBALREPOPASSWORD
      value: {{ k8up_restic_password }}
    - name: BACKUP_GLOBALACCESSKEYID
      value: {{ backup_minio_accesskey }}
    - name: BACKUP_GLOBALSECRETACCESSKEY
      value: {{ backup_minio_accesskey }}
    - name: BACKUP_GLOBALS3ENDPOINT
      value: https://{{ backup_minio_hostname }}
    - name: BACKUP_GLOBALKEEPJOBS
      value: "{{ k8up_keep_jobs }}"
    - name: BACKUP_PROMURL
      value: https://{{ prometheus_pushgateway_hostname }}
metrics:
  serviceMonitor:
    enabled: true
    namespace: {{ prometheus_operator_namespace }}
    additionalLabels:
      prometheus: default
  prometheusRule:
    enabled: true
    namespace: {{ prometheus_operator_namespace }}
    additionalLabels:
      prometheus: default
